# NumPy for Scientific Python

Julie Butler 

June 2021

Physics Immersion Week

Pre-Reading Notebook **2/4**

Please complete this notebook before class on June 21, 2021.

</br>

If you have any questions while working through this notebook, please feel free to contact Julie BUtler at butle222@msu.edu or Morten Hjorth-Jensen at hjensen@msu.edu.

</br>

If you want to use this notebook in Google Colab click [this link](https://colab.research.google.com/drive/1t1MTpW0jyObueAYuMfNEG6ssKQQ0MBoW?usp=sharing) (make sure you are logged into your Google account).  Once the webpage opens up click `File > Save copy a in Drive'.  Then go to your own Google Drive account and use the copy.

</br>

NumPy (also written as Numpy or numpy) is a library that is often used in Python for scientific applications.  Numpy allows the user the ability to store data in vectors or matrices and to easily perform calculations with these data structures.

## Importing Numpy

We covered the four methods of importing a library in the previous notebook.  While all four methods are valid for importing the NumPy library, the code cell below shows the import statement that almost all Python programmers use.



In [2]:
import numpy as np

## Arrays

An array is a Python structure that holds a string of data. Arrays are commonly used in scientific Python.  It is useful because they can be used to represent either a vector or a matrix (if these words are not familiar to you don't worry!  We will cover basic linear algebra concepts during class.).  A vector is a one dimensional string of numbers and a matrix is a two dimensional "table" of numbers.  You can also think of a matrix as a vector of vectors.

### Creating Arrays

Vectors are extremely useful in physics and we will be using them a lot this week.  In programming we use a structure called an array to represent a vector.  NumPy makes it very easy to create an array (but note you have to have the `[]` inside the parentheses).  To make an array with three numbers, you can do the following. Each of the numbers in the array is referred to as an element of that array (i.e. 1.25 is the first element in my_array).


In [ ]:
my_array = np.array([1.25, 2.5, 3.75])
print(my_array)

[1 2 3]


NumPy arrays can be made with any number of elements you like, and they don't have to contain just numbers.  You can also make an array that contains strings.

In [ ]:
my_array_of_numbers = np.array([1, 2, 3, 4, 5])
my_array_of_strings = np.array(['Julie', 'Morten', 'Linda', 'Yani'])

print(my_array_of_numbers)
print(my_array_of_strings)

Additionally, each element in an array can be another array.  We call this a 2D array and they are used in scientific applications to represent matrices.  Carefully note where brackets are in the below statement as that is important to setting up a 2D array correctly.

In [ ]:
my_2d_array = np.array([[1,2,3], [4,5,6]])

print(my_2d_array)

<class 'numpy.ndarray'>


**EXERCISE 1:** In the code cell below use NumPy to create an array.  It can contain as many elements as you like and they can be numbers, strings, or arrays.  After you create the array, print it out and make sure it is storing the elements that you think it should.

### Finding Length of Arrays

There are times where you will want to know the length of an array you have created.  Since arrays can have variable length that may change during the program, we need a way to computationally find its length.  Luckily, finding the length of an array in Python is fairly easy.  Given an array named `my_array`, the length of the array can be found simply by:

In [ ]:
my_array = np.array([1, 2, 3])
print("The length of my_array is", len(my_array))

The length of my_array is 3


The `len()` statement allows you to simply find the length on an array.  Note that this only gives you the lenght of the outer dimension of the array, so for a 2D array it will only tell you the number of rows, but not the number of columns.

In [ ]:
my_2d_array = np.array([[1,2,3], [4,5,6]])
print(len(my_2d_array))

2


An alternative to `len()` is `.shape` which will give the number of rows and the number of columns of a 2D array all at once.

In [ ]:
print(my_2d_array.shape)

(2, 3)


**EXERCISE 2:** Create an array containing any elements in the code cell below (numbers, strings, or a 2D array).  Print the lenght of the array using the `len()` function then print the shape using the `.shape` keyword.

### Array Indexing

Array indexing is a method to extract specific elements from an array.  Each element in an array is assigned an index that describes its location in the array.  The first element in an array has index 0, the second element in the array has index 1, and so on.  Note that the indexes, like many other things in programming begins counting at zero.  To extract an element from an array given an index you can use the following method, where the index of interest goes in square brackets right after the name of the array:

In [ ]:
my_array = np.array([1, 2, 3, 4, 5])

index = 3

my_element = my_array[index]

print(my_element)

4


Remember that using an index of three will give me the fourth element of my array since indexing starts numbering from zero.

When extracting a single element from a 2D array, you need to use a set of double index calls.  The first index call tells which row the number is on (or which inner array it is is) and the second number tells which column (or its location in the inner array). See the example below:

In [ ]:
# Create a 2D array
my_2d_array = np.asarray([[1, 2, 3],[4, 5, 6]])

# Let's see what happens when we only use a single index
test1 = my_2d_array[0]

print ("With a single index call my result is", test1)

# Now let's see what happens when we use a double index call
test2 = my_2d_array[0][0]

print("With a double index call my result is", test2)

With a single index call my result is [1 2 3]
With a double index call my result is 1


When we have a double array and use a single index call, we get one of the innder arrays.  This makes sense since a double array is just an array with all of its elements set to other arrays.  When we use a double index call on a 2D array we get back one number.

**EXERCISE 3:** Create a 2D array that has at least three inner arrays, each with three elements.  Using array indexing, print out the first row (i.e. the first inner array).  Then using array indexing, print out the second element of the third inner array.

### Creating Arrays Through NumPy.Zeros

### Looping Through Arrays

Many applications of NumPy arrays will require making changes to every element of the array.  Typically this is done with a for loop, and there are two commonly used ways to set up a for loop for this task.

#### Method 1: Array Indexing

The first method of looping through an array simply involves using the variable in the for loop as the index to access each element of the array in order.  We simply set the bounds of the `range` statement to start with an index of zero and to stop when the index is equal to the lenght of the array (since the largest possible index an array can have is its length minus one).  In practice we can do something like this to loop through an array:

In [ ]:
# Create an araray
my_array = np.array([1, 2, 3, 4, 5])

# Find length of array
length = len(my_array)

# Use the range statement to loop over all possible indexes 
for i in range(0, length):
    # Print the element at the current index
    print(my_array[i])
    # Change the element at the current index
    my_array[i] = my_array[i]*i

print ("The new array is", my_array)

1
2
3
4
5
The new array is [ 0  2  6 12 20]


Note that changes to the element in the for loop remain once the loop has finished.  

#### Method 2: Direct Looping

The second method of looping through an array requires a small change in the for statement.  Instead of using the `range` statement after the `in` keyword, we simple type the name of our array.  This method of setting up the for loop means that the variable that is declared after the `for` keyword sequentially takes on the value of each element in the array in order.  Let's see how this works in practice.

In [ ]:
# Create a new array
names_array = np.array(['Julie', 'Morten', 'Linda', 'Christian'])

# Use the for statement to loop over each element of the array
for name in names_array:
    # Print out the current element
    print("The name of my teacher is", name)
    # Change the current element
    name = 'Bob'

print('The array after the loop is', names_array)

The name of my teacher is Julie
The name of my teacher is Morten
The name of my teacher is Linda
The name of my teacher is Christian
The array after the loop is ['Julie' 'Morten' 'Linda' 'Christian']


When using this method of iterating through a for loop, you cannot change the value of the elements in the array.  In practice you will typically use the "direct looping" method when you do not want to change the values stored in the array and the "array indexing" method when you do want to change the values.  Both methods can be very useful in their specific applications.

**EXERCISE 4:** Create an array containing any elements in the code cell below.  Then use the "array indexing" method to loop through each element of the array and somehow change them.  Finally use the "direct looping" method to individually print each element of the changed array.

## Operators with NumPy Arrays

NumPy provides many ways to manipulate arrays.  You can read about that [here](http://scipy-lectures.org/intro/numpy/operations.html#sorting-data), but this notebook will only cover two methods that will be used in this week's classes: finding the minimum and maximum element and performing math with arrays.

### Finding Minimums and Maximums

A common problem in physics is to find the maximum or a minimum or some calculation.  You are already familiar with this type of calculation from an introductory mechanics class (ex. how high does the ball go after being kicked).  Since physical data is often stored in NumPy arrays in Python programs, it will be useful to have a way to find the maximum and minimum elements of the array.  Luckily NumPy has an easy way to accomplish this throuhg `np.min` and `np.max`.


In [ ]:
# Create an array of numbers
my_data = np.array([3.4, 7.34, 2.4, 8.54, 4.32, 7.3])
# Find the element with the highest value in the array
print("The largest number in the array is", np.max(my_data))
# Find the element with the lowest value in the array
print("The smallest number in the array is", np.min(my_data))

The largest number in the array is 8.54
The smallest number in the array is 2.4


**EXERCISE 5:** Create a NumPy array in the code cell below.  Then print out the minimum and maximum elements in the array using `np.min` and `np.max`.

### Doing Math with Arrays

#### Basics Equations


NumPy arrays can be used be used much like variables can in an equation.  For example, if I make the variables a and b to represent numbers, then I can do the following:




In [ ]:
# Create two variables
a = 1.25
b = 3.6

# Add and subtract the two variables
add = a+b
subtract = a-b

# Print the results
print(add)
print(subtract)

We can use variables that equal numbers in math equation.  Likewise, we can do a very similar thing with arrays (just note that the arrays have to be the same dimension).

In [3]:
# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Add and subtract the two variables
add = a+b
subtract = a-b

# Print the results
print(add)
print(subtract)

[5 7 9]
[-3 -3 -3]


There are also other ways to do basic mathematics with arrays.  For example I can add 3 to every element in an array with the following syntax:

In [4]:
a = np.array([1, 2, 3, 4])
a = a + 3
print(a)

[4 5 6 7]


I can also use NumPy arrays as variables in equations.  For example, if I wanted to make some data that matched a cubic equation I can do the following (the `**` symbol is an exponent):

In [5]:
x = np.array([1, 2, 3, 4, 5, 6])

y = x**3 + 2*x**2

print(y)

[  3  16  45  96 175 288]


**EXERCISE 6:** Make two 1D arrays of the same length, call them a and b.

1. Add them together and print the result.
2. Multiply a by 2 and divide b by 4.  Print the new values of a and b
3. Plug a into any quadratic equation and print the resulting data.